name: tilepy
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - astropy
  - pytz
  - scipy
  - ipython
  - numpy
  - pandas
  - pytz
  - healpy==1.16.2
  - pytables
  - fastparquet
  - skyfield
  - ipykernel
  - ephem
  - mhealpy>=0.3.0,<0.4
  - ligo.skymap>=2.0.0
  - matplotlib<3.9.0
  - mocpy
